version: 2.1

jobs:
  sleep:
    parameters:
      x:
        type: 'integer'
        default: 0
      y:
        type: 'integer'
        default: 0
      z:
        type: 'integer'
        default: 0
    docker:
      - image: 'alpine'
    steps:
      - run: 'sleep 60'

# NOTE:
# Each of the 16 jobs defaults to large, so 1 Nomad client should handle only 1 of these jobs.
workflows:
  test:
    jobs:
      - sleep:
          matrix:
            parameters:
              x:
                - 0
                - 1
                - 2
                - 3
              y:
                - 0
                - 1
                - 2
                - 3
